// app/leistungen/page.tsx
import {
  Code,
  ClipboardCheck,
  SlidersHorizontal,
  Timer,
  RotateCw,
  Database,
  Wrench,
  ShieldCheck,
  BarChart3,
  type LucideIcon,
} from "lucide-react"
import { services } from "@/data/services"

// Map Font Awesome icon names to Lucide React components
const iconMap: Record<string, LucideIcon> = {
  code: Code,
  "clipboard-check": ClipboardCheck,
  "sliders-h": SlidersHorizontal,
  stopwatch: Timer,
  repeat: RotateCw,
  database: Database,
  tools: Wrench,
  "shield-check": ShieldCheck,
  analytics: BarChart3,
}

export default function LeistungenPage() {
  return (
    <section>
      <h1 className="text-3xl md:text-4xl lg:text-5xl font-bold mb-12 uppercase">//Leistungen</h1>
      <div className="flex flex-wrap justify-center">
        {services.map((service) => {
          const IconComponent = iconMap[service.icon] || Code
          return (
            <div key={service.id} className="w-full sm:w-1/2 lg:w-1/3 px-8 py-8 text-center group">
              <div className="flex flex-col items-center">
                <IconComponent
                  className="h-20 w-20 mb-6 text-foreground/70 group-hover:text-primary transition-colors"
                  strokeWidth={1.5}
                />
                <h2 className="text-2xl font-semibold mb-4">{service.title}</h2>
                <p className="text-lg text-muted-foreground">{service.description}</p>
              </div>
            </div>
          )
        })}
      </div>
    </section>
  )
}

// pages/leistungen.vue
<template>
  <section>
    <h1>//Leistungen</h1>
    <div class="flex flex-wrap justify-center">
      <div
        v-for="leistung in leistungen"
        :key="leistung._path"
        class="w-full sm:w-1/3 px-8 py-4 text-center"
      >
        <font-awesome-icon
          v-if="leistung.icon"
          :icon="['fas', getIconName(leistung.icon)]"
          size="5x"
          color="#646464"
        />
        <h2>{{ leistung.title }}</h2>
        <div v-if="leistung.description" v-html="leistung.description" />
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import type { Service } from '~/types/content'

// Map pro icon names to free icon names
const iconMap: Record<string, string> = {
  'analytics': 'chart-line',
  'shield-check': 'shield-alt',
}

function getIconName(icon: string): string {
  return iconMap[icon] || icon
}

// Query content from the content directory
const { data: leistungen } = await useAsyncData('services', () =>
  queryContent<Service>('/services')
    .find()
)
</script>
